<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-1UR5ED5" failures="8" tests="14" name="RestAssuredTest" time="22.44" errors="0" timestamp="2023-10-26T20:59:22 IST">
  <testcase classname="api.tests.DDTests" name="testPostuser" time="2.612"/>
  <testcase classname="api.tests.DDTests" name="testPostuser" time="1.207"/>
  <testcase classname="api.tests.DDTests" name="testPostuser" time="1.151"/>
  <testcase classname="api.tests.DDTests" name="testPostuser" time="1.202"/>
  <testcase classname="api.tests.DDTests" name="testPostuser" time="1.25"/>
  <testcase classname="api.tests.DDTests" name="testDeleteUserByName" time="1.315">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.tests.DDTests.testDeleteUserByName(DDTests.java:37)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteUserByName -->
  <testcase classname="api.tests.DDTests" name="testDeleteUserByName" time="1.141">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.tests.DDTests.testDeleteUserByName(DDTests.java:37)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteUserByName -->
  <testcase classname="api.tests.DDTests" name="testDeleteUserByName" time="1.246">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.tests.DDTests.testDeleteUserByName(DDTests.java:37)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteUserByName -->
  <testcase classname="api.tests.DDTests" name="testDeleteUserByName" time="1.157">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.tests.DDTests.testDeleteUserByName(DDTests.java:37)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteUserByName -->
  <testcase classname="api.tests.DDTests" name="testDeleteUserByName" time="1.203">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.tests.DDTests.testDeleteUserByName(DDTests.java:37)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteUserByName -->
  <testcase classname="api.tests.UserTests" name="testPostUser" time="1.271"/>
  <testcase classname="api.tests.UserTests" name="testgetUser" time="1.448">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.tests.UserTests.testgetUser(UserTests.java:46)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testgetUser -->
  <testcase classname="api.tests.UserTests" name="testUpdateUser" time="2.391">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.tests.UserTests.testUpdateUser(UserTests.java:58)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testUpdateUser -->
  <testcase classname="api.tests.UserTests" name="testDeleteuser" time="1.181">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.tests.UserTests.testDeleteuser(UserTests.java:64)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteuser -->
</testsuite> <!-- RestAssuredTest -->
